spring:
  flyway:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    user: test
    password: test123
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: test
    password: test123
  h2:
    console:
      enabled: true
  graphql:
    graphiql:
      enabled: true
    schema:
      file-extensions: .graphql,.gql
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
logging:
  level:
    com.querydsl.sql: DEBUG
    org.hibernate.sql: DEBUG
